Insert into Circuit values('C0001', ' Nous parcourerons Paris et Moscou', 'Paris', 'France', 'Moscou', 'Russie', 27, 2499);
Insert into Circuit values('C0002', ' Nous parcourerons Paris et New Delhi', 'Paris', 'France', 'New Delhi', 'Inde', 11, 2138);
Insert into Circuit values('C0003', ' Nous parcourerons Paris et Londres', 'Paris', 'France', 'Londres', 'Angleterre', 12, 2556);
Insert into Circuit values('C0004', ' Nous parcourerons Paris  et Rio', 'Paris', 'France', 'Rio de Janeiro', 'Bresil', 15, 2106);
Insert into Circuit values('C0005', ' Nous parcourerons Paris et Amsterdam', 'Paris', 'France', 'Amsterdam', 'Pays-Bas', 17, 1816);
Insert into Circuit values('C0006', ' Nous parcourerons Paris et New York', 'Paris', 'France', 'New York', 'Etats-Unis', 12, 2014);
Insert into Circuit values('C0007', ' Nous parcourerons Paris et Tanger', 'Paris', 'France', 'Tanger', 'Maroc', 16, 1255);
Insert into Circuit values('C0008', ' Nous parcourerons Paris et Tokyo', 'Paris', 'France', 'Tokyo', 'Japon', 22, 1833);
Insert into Circuit values('C0009', ' Nous parcourerons Paris et Madrid', 'Paris', 'France', 'Madrid', 'Espagne', 25, 2942);
Insert into Circuit values('C0010', ' Nous parcourerons Moscou et Paris', 'Moscou', 'Russie', 'Paris', 'France', 15, 2113);
Insert into Circuit values('C0011', ' Nous parcourerons Moscou et New Delhi', 'Moscou', 'Russie', 'New Delhi', 'Inde', 13, 1210);
Insert into Circuit values('C0012', ' Nous parcourerons Moscou et Londres', 'Moscou', 'Russie', 'Londres', 'Angleterre', 9, 1241);
Insert into Circuit values('C0013', ' Nous parcourerons Moscou  et Rio', 'Moscou', 'Russie', 'Rio de Janeiro', 'Bresil', 8, 2219);
Insert into Circuit values('C0014', ' Nous parcourerons Moscou et Amsterdam', 'Moscou', 'Russie', 'Amsterdam', 'Pays-Bas', 8, 1778);
Insert into Circuit values('C0015', ' Nous parcourerons Moscou et New York', 'Moscou', 'Russie', 'New York', 'Etats-Unis', 10, 1913);
Insert into Circuit values('C0016', ' Nous parcourerons Moscou et Tanger', 'Moscou', 'Russie', 'Tanger', 'Maroc', 21, 1395);
Insert into Circuit values('C0017', ' Nous parcourerons Moscou et Tokyo', 'Moscou', 'Russie', 'Tokyo', 'Japon', 23, 1342);
Insert into Circuit values('C0018', ' Nous parcourerons Moscou et Madrid', 'Moscou', 'Russie', 'Madrid', 'Espagne', 9, 2904);
Insert into Circuit values('C0019', ' Nous parcourerons New Delhi et Paris', 'New Delhi', 'Inde', 'Paris', 'France', 21, 2205);
Insert into Circuit values('C0020', ' Nous parcourerons New Delhi et Moscou', 'New Delhi', 'Inde', 'Moscou', 'Russie', 18, 2816);
Insert into Circuit values('C0021', ' Nous parcourerons New Delhi et Londres', 'New Delhi', 'Inde', 'Londres', 'Angleterre', 28, 1699);
Insert into Circuit values('C0022', ' Nous parcourerons New Delhi  et Rio', 'New Delhi', 'Inde', 'Rio de Janeiro', 'Bresil', 10, 2966);
Insert into Circuit values('C0023', ' Nous parcourerons New Delhi et Amsterdam', 'New Delhi', 'Inde', 'Amsterdam', 'Pays-Bas', 28, 2875);
Insert into Circuit values('C0024', ' Nous parcourerons New Delhi et New York', 'New Delhi', 'Inde', 'New York', 'Etats-Unis', 25, 2691);
Insert into Circuit values('C0025', ' Nous parcourerons New Delhi et Tanger', 'New Delhi', 'Inde', 'Tanger', 'Maroc', 8, 2926);
Insert into Circuit values('C0026', ' Nous parcourerons New Delhi et Tokyo', 'New Delhi', 'Inde', 'Tokyo', 'Japon', 20, 2665);
Insert into Circuit values('C0027', ' Nous parcourerons New Delhi et Madrid', 'New Delhi', 'Inde', 'Madrid', 'Espagne', 13, 1385);
Insert into Circuit values('C0028', ' Nous parcourerons Londres et Paris', 'Londres', 'Angleterre', 'Paris', 'France', 15, 2726);
Insert into Circuit values('C0029', ' Nous parcourerons Londres et Moscou', 'Londres', 'Angleterre', 'Moscou', 'Russie', 20, 1434);
Insert into Circuit values('C0030', ' Nous parcourerons Londres et New Delhi', 'Londres', 'Angleterre', 'New Delhi', 'Inde', 30, 2659);
Insert into Circuit values('C0031', ' Nous parcourerons Londres  et Rio', 'Londres', 'Angleterre', 'Rio de Janeiro', 'Bresil', 18, 2680);
Insert into Circuit values('C0032', ' Nous parcourerons Londres et Amsterdam', 'Londres', 'Angleterre', 'Amsterdam', 'Pays-Bas', 8, 2412);
Insert into Circuit values('C0033', ' Nous parcourerons Londres et New York', 'Londres', 'Angleterre', 'New York', 'Etats-Unis', 22, 2730);
Insert into Circuit values('C0034', ' Nous parcourerons Londres et Tanger', 'Londres', 'Angleterre', 'Tanger', 'Maroc', 24, 1245);
Insert into Circuit values('C0035', ' Nous parcourerons Londres et Tokyo', 'Londres', 'Angleterre', 'Tokyo', 'Japon', 20, 2100);
Insert into Circuit values('C0036', ' Nous parcourerons Londres et Madrid', 'Londres', 'Angleterre', 'Madrid', 'Espagne', 9, 2584);
Insert into Circuit values('C0037', ' Nous parcourerons Rio et Paris', 'Rio de Janeiro', 'Bresil', 'Paris', 'France', 12, 1705);
Insert into Circuit values('C0038', ' Nous parcourerons Rio et Moscou', 'Rio de Janeiro', 'Bresil', 'Moscou', 'Russie', 14, 2035);
Insert into Circuit values('C0039', ' Nous parcourerons Rio et New Delhi', 'Rio de Janeiro', 'Bresil', 'New Delhi', 'Inde', 21, 2676);
Insert into Circuit values('C0040', ' Nous parcourerons Rio et Londres', 'Rio de Janeiro', 'Bresil', 'Londres', 'Angleterre', 30, 2085);
Insert into Circuit values('C0041', ' Nous parcourerons Rio et Amsterdam', 'Rio de Janeiro', 'Bresil', 'Amsterdam', 'Pays-Bas', 9, 1650);
Insert into Circuit values('C0042', ' Nous parcourerons Rio et New York', 'Rio de Janeiro', 'Bresil', 'New York', 'Etats-Unis', 24, 1875);
Insert into Circuit values('C0043', ' Nous parcourerons Rio et Tanger', 'Rio de Janeiro', 'Bresil', 'Tanger', 'Maroc', 12, 2852);
Insert into Circuit values('C0044', ' Nous parcourerons Rio et Tokyo', 'Rio de Janeiro', 'Bresil', 'Tokyo', 'Japon', 10, 1592);
Insert into Circuit values('C0045', ' Nous parcourerons Rio et Madrid', 'Rio de Janeiro', 'Bresil', 'Madrid', 'Espagne', 23, 2961);
Insert into Circuit values('C0046', ' Nous parcourerons Amsterdam et Paris', 'Amsterdam', 'Pays-Bas', 'Paris', 'France', 23, 2763);
Insert into Circuit values('C0047', ' Nous parcourerons Amsterdam et Moscou', 'Amsterdam', 'Pays-Bas', 'Moscou', 'Russie', 12, 1875);
Insert into Circuit values('C0048', ' Nous parcourerons Amsterdam et New Delhi', 'Amsterdam', 'Pays-Bas', 'New Delhi', 'Inde', 25, 2797);
Insert into Circuit values('C0049', ' Nous parcourerons Amsterdam et Londres', 'Amsterdam', 'Pays-Bas', 'Londres', 'Angleterre', 9, 2675);
Insert into Circuit values('C0050', ' Nous parcourerons Amsterdam  et Rio', 'Amsterdam', 'Pays-Bas', 'Rio de Janeiro', 'Bresil', 28, 2858);
Insert into Circuit values('C0051', ' Nous parcourerons Amsterdam et New York', 'Amsterdam', 'Pays-Bas', 'New York', 'Etats-Unis', 17, 1926);
Insert into Circuit values('C0052', ' Nous parcourerons Amsterdam et Tanger', 'Amsterdam', 'Pays-Bas', 'Tanger', 'Maroc', 17, 1650);
Insert into Circuit values('C0053', ' Nous parcourerons Amsterdam et Tokyo', 'Amsterdam', 'Pays-Bas', 'Tokyo', 'Japon', 30, 1290);
Insert into Circuit values('C0054', ' Nous parcourerons Amsterdam et Madrid', 'Amsterdam', 'Pays-Bas', 'Madrid', 'Espagne', 8, 1853);
Insert into Circuit values('C0055', ' Nous parcourerons New York et Paris', 'New York', 'Etats-Unis', 'Paris', 'France', 13, 1537);
Insert into Circuit values('C0056', ' Nous parcourerons New York et Moscou', 'New York', 'Etats-Unis', 'Moscou', 'Russie', 17, 1213);
Insert into Circuit values('C0057', ' Nous parcourerons New York et New Delhi', 'New York', 'Etats-Unis', 'New Delhi', 'Inde', 27, 1443);
Insert into Circuit values('C0058', ' Nous parcourerons New York et Londres', 'New York', 'Etats-Unis', 'Londres', 'Angleterre', 18, 2343);
Insert into Circuit values('C0059', ' Nous parcourerons New York  et Rio', 'New York', 'Etats-Unis', 'Rio de Janeiro', 'Bresil', 12, 2291);
Insert into Circuit values('C0060', ' Nous parcourerons New York et Amsterdam', 'New York', 'Etats-Unis', 'Amsterdam', 'Pays-Bas', 16, 2439);
Insert into Circuit values('C0061', ' Nous parcourerons New York et Tanger', 'New York', 'Etats-Unis', 'Tanger', 'Maroc', 26, 2457);
Insert into Circuit values('C0062', ' Nous parcourerons New York et Tokyo', 'New York', 'Etats-Unis', 'Tokyo', 'Japon', 18, 2857);
Insert into Circuit values('C0063', ' Nous parcourerons New York et Madrid', 'New York', 'Etats-Unis', 'Madrid', 'Espagne', 26, 2321);
Insert into Circuit values('C0064', ' Nous parcourerons Tanger et Paris', 'Tanger', 'Maroc', 'Paris', 'France', 8, 1882);
Insert into Circuit values('C0065', ' Nous parcourerons Tanger et Moscou', 'Tanger', 'Maroc', 'Moscou', 'Russie', 15, 1937);
Insert into Circuit values('C0066', ' Nous parcourerons Tanger et New Delhi', 'Tanger', 'Maroc', 'New Delhi', 'Inde', 27, 1378);
Insert into Circuit values('C0067', ' Nous parcourerons Tanger et Londres', 'Tanger', 'Maroc', 'Londres', 'Angleterre', 21, 2420);
Insert into Circuit values('C0068', ' Nous parcourerons Tanger  et Rio', 'Tanger', 'Maroc', 'Rio de Janeiro', 'Bresil', 19, 2993);
Insert into Circuit values('C0069', ' Nous parcourerons Tanger et Amsterdam', 'Tanger', 'Maroc', 'Amsterdam', 'Pays-Bas', 25, 2440);
Insert into Circuit values('C0070', ' Nous parcourerons Tanger et New York', 'Tanger', 'Maroc', 'New York', 'Etats-Unis', 14, 2565);
Insert into Circuit values('C0071', ' Nous parcourerons Tanger et Tokyo', 'Tanger', 'Maroc', 'Tokyo', 'Japon', 8, 1783);
Insert into Circuit values('C0072', ' Nous parcourerons Tanger et Madrid', 'Tanger', 'Maroc', 'Madrid', 'Espagne', 14, 2292);
Insert into Circuit values('C0073', ' Nous parcourerons Tokyo et Paris', 'Tokyo', 'Japon', 'Paris', 'France', 17, 1224);
Insert into Circuit values('C0074', ' Nous parcourerons Tokyo et Moscou', 'Tokyo', 'Japon', 'Moscou', 'Russie', 28, 1261);
Insert into Circuit values('C0075', ' Nous parcourerons Tokyo et New Delhi', 'Tokyo', 'Japon', 'New Delhi', 'Inde', 22, 2667);
Insert into Circuit values('C0076', ' Nous parcourerons Tokyo et Londres', 'Tokyo', 'Japon', 'Londres', 'Angleterre', 17, 2143);
Insert into Circuit values('C0077', ' Nous parcourerons Tokyo  et Rio', 'Tokyo', 'Japon', 'Rio de Janeiro', 'Bresil', 19, 1618);
Insert into Circuit values('C0078', ' Nous parcourerons Tokyo et Amsterdam', 'Tokyo', 'Japon', 'Amsterdam', 'Pays-Bas', 24, 2706);
Insert into Circuit values('C0079', ' Nous parcourerons Tokyo et New York', 'Tokyo', 'Japon', 'New York', 'Etats-Unis', 30, 1254);
Insert into Circuit values('C0080', ' Nous parcourerons Tokyo et Tanger', 'Tokyo', 'Japon', 'Tanger', 'Maroc', 22, 2659);
Insert into Circuit values('C0081', ' Nous parcourerons Tokyo et Madrid', 'Tokyo', 'Japon', 'Madrid', 'Espagne', 8, 2023);
Insert into Circuit values('C0082', ' Nous parcourerons Madrid et Paris', 'Madrid', 'Espagne', 'Paris', 'France', 26, 2039);
Insert into Circuit values('C0083', ' Nous parcourerons Madrid et Moscou', 'Madrid', 'Espagne', 'Moscou', 'Russie', 13, 2725);
Insert into Circuit values('C0084', ' Nous parcourerons Madrid et New Delhi', 'Madrid', 'Espagne', 'New Delhi', 'Inde', 21, 2467);
Insert into Circuit values('C0085', ' Nous parcourerons Madrid et Londres', 'Madrid', 'Espagne', 'Londres', 'Angleterre', 23, 2524);
Insert into Circuit values('C0086', ' Nous parcourerons Madrid  et Rio', 'Madrid', 'Espagne', 'Rio de Janeiro', 'Bresil', 13, 2173);
Insert into Circuit values('C0087', ' Nous parcourerons Madrid et Amsterdam', 'Madrid', 'Espagne', 'Amsterdam', 'Pays-Bas', 10, 2792);
Insert into Circuit values('C0088', ' Nous parcourerons Madrid et New York', 'Madrid', 'Espagne', 'New York', 'Etats-Unis', 14, 2880);
Insert into Circuit values('C0089', ' Nous parcourerons Madrid et Tanger', 'Madrid', 'Espagne', 'Tanger', 'Maroc', 10, 1738);
Insert into Circuit values('C0090', ' Nous parcourerons Madrid et Tokyo', 'Madrid', 'Espagne', 'Tokyo', 'Japon', 24, 2806);
