Insert into Etapes values('C0001', 1, 'Tour Eiffel', 'Paris', 'France',  6);
Insert into Etapes values('C0001', 2, 'Champs-elysees', 'Paris', 'France',  6);
Insert into Etapes values('C0001', 3, 'Kremlin de Moscou', 'Moscou', 'Russie',  6);
Insert into Etapes values('C0001', 4, 'Parc Gorki', 'Moscou', 'Russie',  21);
Insert into Etapes values('C0002', 1, 'Tour Eiffel', 'Paris', 'France',  2);
Insert into Etapes values('C0002', 2, 'Champs-elysees', 'Paris', 'France',  2);
Insert into Etapes values('C0002', 3, 'Fort Rouge', 'New Delhi', 'Inde',  2);
Insert into Etapes values('C0002', 4, 'Qutb Minar', 'New Delhi', 'Inde',  9);
Insert into Etapes values('C0003', 1, 'Tour Eiffel', 'Paris', 'France',  3);
Insert into Etapes values('C0003', 2, 'Champs-elysees', 'Paris', 'France',  3);
Insert into Etapes values('C0003', 3, 'Big Ben', 'Londres', 'Angleterre',  3);
Insert into Etapes values('C0003', 4, 'British Museum', 'Londres', 'Angleterre',  9);
Insert into Etapes values('C0004', 1, 'Tour Eiffel', 'Paris', 'France',  3);
Insert into Etapes values('C0004', 2, 'Champs-elysees', 'Paris', 'France',  3);
Insert into Etapes values('C0004', 3, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  3);
Insert into Etapes values('C0004', 4, 'Corcovado', 'Rio de Janeiro', 'Bresil',  12);
Insert into Etapes values('C0005', 1, 'Tour Eiffel', 'Paris', 'France',  4);
Insert into Etapes values('C0005', 2, 'Champs-elysees', 'Paris', 'France',  4);
Insert into Etapes values('C0005', 3, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  4);
Insert into Etapes values('C0005', 4, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  13);
Insert into Etapes values('C0006', 1, 'Tour Eiffel', 'Paris', 'France',  3);
Insert into Etapes values('C0006', 2, 'Champs-elysees', 'Paris', 'France',  3);
Insert into Etapes values('C0006', 3, 'Central Park', 'New York', 'Etats-Unis',  3);
Insert into Etapes values('C0006', 4, 'Statue de la Liberte', 'New York', 'Etats-Unis',  9);
Insert into Etapes values('C0007', 1, 'Tour Eiffel', 'Paris', 'France',  4);
Insert into Etapes values('C0007', 2, 'Champs-elysees', 'Paris', 'France',  4);
Insert into Etapes values('C0007', 3, 'Musee de la Kasbah', 'Tanger', 'Maroc',  4);
Insert into Etapes values('C0007', 4, 'Grottes Hercule', 'Tanger', 'Maroc',  12);
Insert into Etapes values('C0008', 1, 'Tour Eiffel', 'Paris', 'France',  5);
Insert into Etapes values('C0008', 2, 'Champs-elysees', 'Paris', 'France',  5);
Insert into Etapes values('C0008', 3, 'Senso-ji', 'Tokyo', 'Japon',  5);
Insert into Etapes values('C0008', 4, 'Tokyo Skytree', 'Tokyo', 'Japon',  17);
Insert into Etapes values('C0009', 1, 'Tour Eiffel', 'Paris', 'France',  6);
Insert into Etapes values('C0009', 2, 'Champs-elysees', 'Paris', 'France',  6);
Insert into Etapes values('C0009', 3, 'Parc du Retiro', 'Madrid', 'Espagne',  6);
Insert into Etapes values('C0009', 4, 'Puerta del Sol', 'Madrid', 'Espagne',  19);
Insert into Etapes values('C0010', 1, 'Kremlin de Moscou', 'Moscou', 'Russie',  3);
Insert into Etapes values('C0010', 2, 'Parc Gorki', 'Moscou', 'Russie',  3);
Insert into Etapes values('C0010', 3, 'Tour Eiffel', 'Paris', 'France',  3);
Insert into Etapes values('C0010', 4, 'Champs-elysees', 'Paris', 'France',  12);
Insert into Etapes values('C0011', 1, 'Kremlin de Moscou', 'Moscou', 'Russie',  3);
Insert into Etapes values('C0011', 2, 'Parc Gorki', 'Moscou', 'Russie',  3);
Insert into Etapes values('C0011', 3, 'Fort Rouge', 'New Delhi', 'Inde',  3);
Insert into Etapes values('C0011', 4, 'Qutb Minar', 'New Delhi', 'Inde',  10);
Insert into Etapes values('C0012', 1, 'Kremlin de Moscou', 'Moscou', 'Russie',  2);
Insert into Etapes values('C0012', 2, 'Parc Gorki', 'Moscou', 'Russie',  2);
Insert into Etapes values('C0012', 3, 'Big Ben', 'Londres', 'Angleterre',  2);
Insert into Etapes values('C0012', 4, 'British Museum', 'Londres', 'Angleterre',  7);
Insert into Etapes values('C0013', 1, 'Kremlin de Moscou', 'Moscou', 'Russie',  2);
Insert into Etapes values('C0013', 2, 'Parc Gorki', 'Moscou', 'Russie',  2);
Insert into Etapes values('C0013', 3, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  2);
Insert into Etapes values('C0013', 4, 'Corcovado', 'Rio de Janeiro', 'Bresil',  6);
Insert into Etapes values('C0014', 1, 'Kremlin de Moscou', 'Moscou', 'Russie',  2);
Insert into Etapes values('C0014', 2, 'Parc Gorki', 'Moscou', 'Russie',  2);
Insert into Etapes values('C0014', 3, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  2);
Insert into Etapes values('C0014', 4, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  6);
Insert into Etapes values('C0015', 1, 'Kremlin de Moscou', 'Moscou', 'Russie',  2);
Insert into Etapes values('C0015', 2, 'Parc Gorki', 'Moscou', 'Russie',  2);
Insert into Etapes values('C0015', 3, 'Central Park', 'New York', 'Etats-Unis',  2);
Insert into Etapes values('C0015', 4, 'Statue de la Liberte', 'New York', 'Etats-Unis',  8);
Insert into Etapes values('C0016', 1, 'Kremlin de Moscou', 'Moscou', 'Russie',  5);
Insert into Etapes values('C0016', 2, 'Parc Gorki', 'Moscou', 'Russie',  5);
Insert into Etapes values('C0016', 3, 'Musee de la Kasbah', 'Tanger', 'Maroc',  5);
Insert into Etapes values('C0016', 4, 'Grottes Hercule', 'Tanger', 'Maroc',  16);
Insert into Etapes values('C0017', 1, 'Kremlin de Moscou', 'Moscou', 'Russie',  5);
Insert into Etapes values('C0017', 2, 'Parc Gorki', 'Moscou', 'Russie',  5);
Insert into Etapes values('C0017', 3, 'Senso-ji', 'Tokyo', 'Japon',  5);
Insert into Etapes values('C0017', 4, 'Tokyo Skytree', 'Tokyo', 'Japon',  18);
Insert into Etapes values('C0018', 1, 'Kremlin de Moscou', 'Moscou', 'Russie',  2);
Insert into Etapes values('C0018', 2, 'Parc Gorki', 'Moscou', 'Russie',  2);
Insert into Etapes values('C0018', 3, 'Parc du Retiro', 'Madrid', 'Espagne',  2);
Insert into Etapes values('C0018', 4, 'Puerta del Sol', 'Madrid', 'Espagne',  7);
Insert into Etapes values('C0019', 1, 'Fort Rouge', 'New Delhi', 'Inde',  5);
Insert into Etapes values('C0019', 2, 'Qutb Minar', 'New Delhi', 'Inde',  5);
Insert into Etapes values('C0019', 3, 'Tour Eiffel', 'Paris', 'France',  5);
Insert into Etapes values('C0019', 4, 'Champs-elysees', 'Paris', 'France',  16);
Insert into Etapes values('C0020', 1, 'Fort Rouge', 'New Delhi', 'Inde',  4);
Insert into Etapes values('C0020', 2, 'Qutb Minar', 'New Delhi', 'Inde',  4);
Insert into Etapes values('C0020', 3, 'Kremlin de Moscou', 'Moscou', 'Russie',  4);
Insert into Etapes values('C0020', 4, 'Parc Gorki', 'Moscou', 'Russie',  14);
Insert into Etapes values('C0021', 1, 'Fort Rouge', 'New Delhi', 'Inde',  7);
Insert into Etapes values('C0021', 2, 'Qutb Minar', 'New Delhi', 'Inde',  7);
Insert into Etapes values('C0021', 3, 'Big Ben', 'Londres', 'Angleterre',  7);
Insert into Etapes values('C0021', 4, 'British Museum', 'Londres', 'Angleterre',  21);
Insert into Etapes values('C0022', 1, 'Fort Rouge', 'New Delhi', 'Inde',  2);
Insert into Etapes values('C0022', 2, 'Qutb Minar', 'New Delhi', 'Inde',  2);
Insert into Etapes values('C0022', 3, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  2);
Insert into Etapes values('C0022', 4, 'Corcovado', 'Rio de Janeiro', 'Bresil',  8);
Insert into Etapes values('C0023', 1, 'Fort Rouge', 'New Delhi', 'Inde',  7);
Insert into Etapes values('C0023', 2, 'Qutb Minar', 'New Delhi', 'Inde',  7);
Insert into Etapes values('C0023', 3, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  7);
Insert into Etapes values('C0023', 4, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  21);
Insert into Etapes values('C0024', 1, 'Fort Rouge', 'New Delhi', 'Inde',  6);
Insert into Etapes values('C0024', 2, 'Qutb Minar', 'New Delhi', 'Inde',  6);
Insert into Etapes values('C0024', 3, 'Central Park', 'New York', 'Etats-Unis',  6);
Insert into Etapes values('C0024', 4, 'Statue de la Liberte', 'New York', 'Etats-Unis',  19);
Insert into Etapes values('C0025', 1, 'Fort Rouge', 'New Delhi', 'Inde',  2);
Insert into Etapes values('C0025', 2, 'Qutb Minar', 'New Delhi', 'Inde',  2);
Insert into Etapes values('C0025', 3, 'Musee de la Kasbah', 'Tanger', 'Maroc',  2);
Insert into Etapes values('C0025', 4, 'Grottes Hercule', 'Tanger', 'Maroc',  6);
Insert into Etapes values('C0026', 1, 'Fort Rouge', 'New Delhi', 'Inde',  5);
Insert into Etapes values('C0026', 2, 'Qutb Minar', 'New Delhi', 'Inde',  5);
Insert into Etapes values('C0026', 3, 'Senso-ji', 'Tokyo', 'Japon',  5);
Insert into Etapes values('C0026', 4, 'Tokyo Skytree', 'Tokyo', 'Japon',  15);
Insert into Etapes values('C0027', 1, 'Fort Rouge', 'New Delhi', 'Inde',  3);
Insert into Etapes values('C0027', 2, 'Qutb Minar', 'New Delhi', 'Inde',  3);
Insert into Etapes values('C0027', 3, 'Parc du Retiro', 'Madrid', 'Espagne',  3);
Insert into Etapes values('C0027', 4, 'Puerta del Sol', 'Madrid', 'Espagne',  10);
Insert into Etapes values('C0028', 1, 'Big Ben', 'Londres', 'Angleterre',  3);
Insert into Etapes values('C0028', 2, 'British Museum', 'Londres', 'Angleterre',  3);
Insert into Etapes values('C0028', 3, 'Tour Eiffel', 'Paris', 'France',  3);
Insert into Etapes values('C0028', 4, 'Champs-elysees', 'Paris', 'France',  12);
Insert into Etapes values('C0029', 1, 'Big Ben', 'Londres', 'Angleterre',  5);
Insert into Etapes values('C0029', 2, 'British Museum', 'Londres', 'Angleterre',  5);
Insert into Etapes values('C0029', 3, 'Kremlin de Moscou', 'Moscou', 'Russie',  5);
Insert into Etapes values('C0029', 4, 'Parc Gorki', 'Moscou', 'Russie',  15);
Insert into Etapes values('C0030', 1, 'Big Ben', 'Londres', 'Angleterre',  7);
Insert into Etapes values('C0030', 2, 'British Museum', 'Londres', 'Angleterre',  7);
Insert into Etapes values('C0030', 3, 'Fort Rouge', 'New Delhi', 'Inde',  7);
Insert into Etapes values('C0030', 4, 'Qutb Minar', 'New Delhi', 'Inde',  23);
Insert into Etapes values('C0031', 1, 'Big Ben', 'Londres', 'Angleterre',  4);
Insert into Etapes values('C0031', 2, 'British Museum', 'Londres', 'Angleterre',  4);
Insert into Etapes values('C0031', 3, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  4);
Insert into Etapes values('C0031', 4, 'Corcovado', 'Rio de Janeiro', 'Bresil',  14);
Insert into Etapes values('C0032', 1, 'Big Ben', 'Londres', 'Angleterre',  2);
Insert into Etapes values('C0032', 2, 'British Museum', 'Londres', 'Angleterre',  2);
Insert into Etapes values('C0032', 3, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  2);
Insert into Etapes values('C0032', 4, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  6);
Insert into Etapes values('C0033', 1, 'Big Ben', 'Londres', 'Angleterre',  5);
Insert into Etapes values('C0033', 2, 'British Museum', 'Londres', 'Angleterre',  5);
Insert into Etapes values('C0033', 3, 'Central Park', 'New York', 'Etats-Unis',  5);
Insert into Etapes values('C0033', 4, 'Statue de la Liberte', 'New York', 'Etats-Unis',  17);
Insert into Etapes values('C0034', 1, 'Big Ben', 'Londres', 'Angleterre',  6);
Insert into Etapes values('C0034', 2, 'British Museum', 'Londres', 'Angleterre',  6);
Insert into Etapes values('C0034', 3, 'Musee de la Kasbah', 'Tanger', 'Maroc',  6);
Insert into Etapes values('C0034', 4, 'Grottes Hercule', 'Tanger', 'Maroc',  18);
Insert into Etapes values('C0035', 1, 'Big Ben', 'Londres', 'Angleterre',  5);
Insert into Etapes values('C0035', 2, 'British Museum', 'Londres', 'Angleterre',  5);
Insert into Etapes values('C0035', 3, 'Senso-ji', 'Tokyo', 'Japon',  5);
Insert into Etapes values('C0035', 4, 'Tokyo Skytree', 'Tokyo', 'Japon',  15);
Insert into Etapes values('C0036', 1, 'Big Ben', 'Londres', 'Angleterre',  2);
Insert into Etapes values('C0036', 2, 'British Museum', 'Londres', 'Angleterre',  2);
Insert into Etapes values('C0036', 3, 'Parc du Retiro', 'Madrid', 'Espagne',  2);
Insert into Etapes values('C0036', 4, 'Puerta del Sol', 'Madrid', 'Espagne',  7);
Insert into Etapes values('C0037', 1, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  3);
Insert into Etapes values('C0037', 2, 'Corcovado', 'Rio de Janeiro', 'Bresil',  3);
Insert into Etapes values('C0037', 3, 'Tour Eiffel', 'Paris', 'France',  3);
Insert into Etapes values('C0037', 4, 'Champs-elysees', 'Paris', 'France',  9);
Insert into Etapes values('C0038', 1, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  3);
Insert into Etapes values('C0038', 2, 'Corcovado', 'Rio de Janeiro', 'Bresil',  3);
Insert into Etapes values('C0038', 3, 'Kremlin de Moscou', 'Moscou', 'Russie',  3);
Insert into Etapes values('C0038', 4, 'Parc Gorki', 'Moscou', 'Russie',  11);
Insert into Etapes values('C0039', 1, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  5);
Insert into Etapes values('C0039', 2, 'Corcovado', 'Rio de Janeiro', 'Bresil',  5);
Insert into Etapes values('C0039', 3, 'Fort Rouge', 'New Delhi', 'Inde',  5);
Insert into Etapes values('C0039', 4, 'Qutb Minar', 'New Delhi', 'Inde',  16);
Insert into Etapes values('C0040', 1, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  7);
Insert into Etapes values('C0040', 2, 'Corcovado', 'Rio de Janeiro', 'Bresil',  7);
Insert into Etapes values('C0040', 3, 'Big Ben', 'Londres', 'Angleterre',  7);
Insert into Etapes values('C0040', 4, 'British Museum', 'Londres', 'Angleterre',  23);
Insert into Etapes values('C0041', 1, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  2);
Insert into Etapes values('C0041', 2, 'Corcovado', 'Rio de Janeiro', 'Bresil',  2);
Insert into Etapes values('C0041', 3, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  2);
Insert into Etapes values('C0041', 4, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  7);
Insert into Etapes values('C0042', 1, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  6);
Insert into Etapes values('C0042', 2, 'Corcovado', 'Rio de Janeiro', 'Bresil',  6);
Insert into Etapes values('C0042', 3, 'Central Park', 'New York', 'Etats-Unis',  6);
Insert into Etapes values('C0042', 4, 'Statue de la Liberte', 'New York', 'Etats-Unis',  18);
Insert into Etapes values('C0043', 1, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  3);
Insert into Etapes values('C0043', 2, 'Corcovado', 'Rio de Janeiro', 'Bresil',  3);
Insert into Etapes values('C0043', 3, 'Musee de la Kasbah', 'Tanger', 'Maroc',  3);
Insert into Etapes values('C0043', 4, 'Grottes Hercule', 'Tanger', 'Maroc',  9);
Insert into Etapes values('C0044', 1, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  2);
Insert into Etapes values('C0044', 2, 'Corcovado', 'Rio de Janeiro', 'Bresil',  2);
Insert into Etapes values('C0044', 3, 'Senso-ji', 'Tokyo', 'Japon',  2);
Insert into Etapes values('C0044', 4, 'Tokyo Skytree', 'Tokyo', 'Japon',  8);
Insert into Etapes values('C0045', 1, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  5);
Insert into Etapes values('C0045', 2, 'Corcovado', 'Rio de Janeiro', 'Bresil',  5);
Insert into Etapes values('C0045', 3, 'Parc du Retiro', 'Madrid', 'Espagne',  5);
Insert into Etapes values('C0045', 4, 'Puerta del Sol', 'Madrid', 'Espagne',  18);
Insert into Etapes values('C0046', 1, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  5);
Insert into Etapes values('C0046', 2, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  5);
Insert into Etapes values('C0046', 3, 'Tour Eiffel', 'Paris', 'France',  5);
Insert into Etapes values('C0046', 4, 'Champs-elysees', 'Paris', 'France',  18);
Insert into Etapes values('C0047', 1, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  3);
Insert into Etapes values('C0047', 2, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  3);
Insert into Etapes values('C0047', 3, 'Kremlin de Moscou', 'Moscou', 'Russie',  3);
Insert into Etapes values('C0047', 4, 'Parc Gorki', 'Moscou', 'Russie',  9);
Insert into Etapes values('C0048', 1, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  6);
Insert into Etapes values('C0048', 2, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  6);
Insert into Etapes values('C0048', 3, 'Fort Rouge', 'New Delhi', 'Inde',  6);
Insert into Etapes values('C0048', 4, 'Qutb Minar', 'New Delhi', 'Inde',  19);
Insert into Etapes values('C0049', 1, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  2);
Insert into Etapes values('C0049', 2, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  2);
Insert into Etapes values('C0049', 3, 'Big Ben', 'Londres', 'Angleterre',  2);
Insert into Etapes values('C0049', 4, 'British Museum', 'Londres', 'Angleterre',  7);
Insert into Etapes values('C0050', 1, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  7);
Insert into Etapes values('C0050', 2, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  7);
Insert into Etapes values('C0050', 3, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  7);
Insert into Etapes values('C0050', 4, 'Corcovado', 'Rio de Janeiro', 'Bresil',  21);
Insert into Etapes values('C0051', 1, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  4);
Insert into Etapes values('C0051', 2, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  4);
Insert into Etapes values('C0051', 3, 'Central Park', 'New York', 'Etats-Unis',  4);
Insert into Etapes values('C0051', 4, 'Statue de la Liberte', 'New York', 'Etats-Unis',  13);
Insert into Etapes values('C0052', 1, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  4);
Insert into Etapes values('C0052', 2, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  4);
Insert into Etapes values('C0052', 3, 'Musee de la Kasbah', 'Tanger', 'Maroc',  4);
Insert into Etapes values('C0052', 4, 'Grottes Hercule', 'Tanger', 'Maroc',  13);
Insert into Etapes values('C0053', 1, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  7);
Insert into Etapes values('C0053', 2, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  7);
Insert into Etapes values('C0053', 3, 'Senso-ji', 'Tokyo', 'Japon',  7);
Insert into Etapes values('C0053', 4, 'Tokyo Skytree', 'Tokyo', 'Japon',  23);
Insert into Etapes values('C0054', 1, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  2);
Insert into Etapes values('C0054', 2, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  2);
Insert into Etapes values('C0054', 3, 'Parc du Retiro', 'Madrid', 'Espagne',  2);
Insert into Etapes values('C0054', 4, 'Puerta del Sol', 'Madrid', 'Espagne',  6);
Insert into Etapes values('C0055', 1, 'Central Park', 'New York', 'Etats-Unis',  3);
Insert into Etapes values('C0055', 2, 'Statue de la Liberte', 'New York', 'Etats-Unis',  3);
Insert into Etapes values('C0055', 3, 'Tour Eiffel', 'Paris', 'France',  3);
Insert into Etapes values('C0055', 4, 'Champs-elysees', 'Paris', 'France',  10);
Insert into Etapes values('C0056', 1, 'Central Park', 'New York', 'Etats-Unis',  4);
Insert into Etapes values('C0056', 2, 'Statue de la Liberte', 'New York', 'Etats-Unis',  4);
Insert into Etapes values('C0056', 3, 'Kremlin de Moscou', 'Moscou', 'Russie',  4);
Insert into Etapes values('C0056', 4, 'Parc Gorki', 'Moscou', 'Russie',  13);
Insert into Etapes values('C0057', 1, 'Central Park', 'New York', 'Etats-Unis',  6);
Insert into Etapes values('C0057', 2, 'Statue de la Liberte', 'New York', 'Etats-Unis',  6);
Insert into Etapes values('C0057', 3, 'Fort Rouge', 'New Delhi', 'Inde',  6);
Insert into Etapes values('C0057', 4, 'Qutb Minar', 'New Delhi', 'Inde',  21);
Insert into Etapes values('C0058', 1, 'Central Park', 'New York', 'Etats-Unis',  4);
Insert into Etapes values('C0058', 2, 'Statue de la Liberte', 'New York', 'Etats-Unis',  4);
Insert into Etapes values('C0058', 3, 'Big Ben', 'Londres', 'Angleterre',  4);
Insert into Etapes values('C0058', 4, 'British Museum', 'Londres', 'Angleterre',  14);
Insert into Etapes values('C0059', 1, 'Central Park', 'New York', 'Etats-Unis',  3);
Insert into Etapes values('C0059', 2, 'Statue de la Liberte', 'New York', 'Etats-Unis',  3);
Insert into Etapes values('C0059', 3, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  3);
Insert into Etapes values('C0059', 4, 'Corcovado', 'Rio de Janeiro', 'Bresil',  9);
Insert into Etapes values('C0060', 1, 'Central Park', 'New York', 'Etats-Unis',  4);
Insert into Etapes values('C0060', 2, 'Statue de la Liberte', 'New York', 'Etats-Unis',  4);
Insert into Etapes values('C0060', 3, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  4);
Insert into Etapes values('C0060', 4, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  12);
Insert into Etapes values('C0061', 1, 'Central Park', 'New York', 'Etats-Unis',  6);
Insert into Etapes values('C0061', 2, 'Statue de la Liberte', 'New York', 'Etats-Unis',  6);
Insert into Etapes values('C0061', 3, 'Musee de la Kasbah', 'Tanger', 'Maroc',  6);
Insert into Etapes values('C0061', 4, 'Grottes Hercule', 'Tanger', 'Maroc',  20);
Insert into Etapes values('C0062', 1, 'Central Park', 'New York', 'Etats-Unis',  4);
Insert into Etapes values('C0062', 2, 'Statue de la Liberte', 'New York', 'Etats-Unis',  4);
Insert into Etapes values('C0062', 3, 'Senso-ji', 'Tokyo', 'Japon',  4);
Insert into Etapes values('C0062', 4, 'Tokyo Skytree', 'Tokyo', 'Japon',  14);
Insert into Etapes values('C0063', 1, 'Central Park', 'New York', 'Etats-Unis',  6);
Insert into Etapes values('C0063', 2, 'Statue de la Liberte', 'New York', 'Etats-Unis',  6);
Insert into Etapes values('C0063', 3, 'Parc du Retiro', 'Madrid', 'Espagne',  6);
Insert into Etapes values('C0063', 4, 'Puerta del Sol', 'Madrid', 'Espagne',  20);
Insert into Etapes values('C0064', 1, 'Musee de la Kasbah', 'Tanger', 'Maroc',  2);
Insert into Etapes values('C0064', 2, 'Grottes Hercule', 'Tanger', 'Maroc',  2);
Insert into Etapes values('C0064', 3, 'Tour Eiffel', 'Paris', 'France',  2);
Insert into Etapes values('C0064', 4, 'Champs-elysees', 'Paris', 'France',  6);
Insert into Etapes values('C0065', 1, 'Musee de la Kasbah', 'Tanger', 'Maroc',  3);
Insert into Etapes values('C0065', 2, 'Grottes Hercule', 'Tanger', 'Maroc',  3);
Insert into Etapes values('C0065', 3, 'Kremlin de Moscou', 'Moscou', 'Russie',  3);
Insert into Etapes values('C0065', 4, 'Parc Gorki', 'Moscou', 'Russie',  12);
Insert into Etapes values('C0066', 1, 'Musee de la Kasbah', 'Tanger', 'Maroc',  6);
Insert into Etapes values('C0066', 2, 'Grottes Hercule', 'Tanger', 'Maroc',  6);
Insert into Etapes values('C0066', 3, 'Fort Rouge', 'New Delhi', 'Inde',  6);
Insert into Etapes values('C0066', 4, 'Qutb Minar', 'New Delhi', 'Inde',  21);
Insert into Etapes values('C0067', 1, 'Musee de la Kasbah', 'Tanger', 'Maroc',  5);
Insert into Etapes values('C0067', 2, 'Grottes Hercule', 'Tanger', 'Maroc',  5);
Insert into Etapes values('C0067', 3, 'Big Ben', 'Londres', 'Angleterre',  5);
Insert into Etapes values('C0067', 4, 'British Museum', 'Londres', 'Angleterre',  16);
Insert into Etapes values('C0068', 1, 'Musee de la Kasbah', 'Tanger', 'Maroc',  4);
Insert into Etapes values('C0068', 2, 'Grottes Hercule', 'Tanger', 'Maroc',  4);
Insert into Etapes values('C0068', 3, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  4);
Insert into Etapes values('C0068', 4, 'Corcovado', 'Rio de Janeiro', 'Bresil',  15);
Insert into Etapes values('C0069', 1, 'Musee de la Kasbah', 'Tanger', 'Maroc',  6);
Insert into Etapes values('C0069', 2, 'Grottes Hercule', 'Tanger', 'Maroc',  6);
Insert into Etapes values('C0069', 3, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  6);
Insert into Etapes values('C0069', 4, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  19);
Insert into Etapes values('C0070', 1, 'Musee de la Kasbah', 'Tanger', 'Maroc',  3);
Insert into Etapes values('C0070', 2, 'Grottes Hercule', 'Tanger', 'Maroc',  3);
Insert into Etapes values('C0070', 3, 'Central Park', 'New York', 'Etats-Unis',  3);
Insert into Etapes values('C0070', 4, 'Statue de la Liberte', 'New York', 'Etats-Unis',  11);
Insert into Etapes values('C0071', 1, 'Musee de la Kasbah', 'Tanger', 'Maroc',  2);
Insert into Etapes values('C0071', 2, 'Grottes Hercule', 'Tanger', 'Maroc',  2);
Insert into Etapes values('C0071', 3, 'Senso-ji', 'Tokyo', 'Japon',  2);
Insert into Etapes values('C0071', 4, 'Tokyo Skytree', 'Tokyo', 'Japon',  6);
Insert into Etapes values('C0072', 1, 'Musee de la Kasbah', 'Tanger', 'Maroc',  3);
Insert into Etapes values('C0072', 2, 'Grottes Hercule', 'Tanger', 'Maroc',  3);
Insert into Etapes values('C0072', 3, 'Parc du Retiro', 'Madrid', 'Espagne',  3);
Insert into Etapes values('C0072', 4, 'Puerta del Sol', 'Madrid', 'Espagne',  11);
Insert into Etapes values('C0073', 1, 'Senso-ji', 'Tokyo', 'Japon',  4);
Insert into Etapes values('C0073', 2, 'Tokyo Skytree', 'Tokyo', 'Japon',  4);
Insert into Etapes values('C0073', 3, 'Tour Eiffel', 'Paris', 'France',  4);
Insert into Etapes values('C0073', 4, 'Champs-elysees', 'Paris', 'France',  13);
Insert into Etapes values('C0074', 1, 'Senso-ji', 'Tokyo', 'Japon',  7);
Insert into Etapes values('C0074', 2, 'Tokyo Skytree', 'Tokyo', 'Japon',  7);
Insert into Etapes values('C0074', 3, 'Kremlin de Moscou', 'Moscou', 'Russie',  7);
Insert into Etapes values('C0074', 4, 'Parc Gorki', 'Moscou', 'Russie',  21);
Insert into Etapes values('C0075', 1, 'Senso-ji', 'Tokyo', 'Japon',  5);
Insert into Etapes values('C0075', 2, 'Tokyo Skytree', 'Tokyo', 'Japon',  5);
Insert into Etapes values('C0075', 3, 'Fort Rouge', 'New Delhi', 'Inde',  5);
Insert into Etapes values('C0075', 4, 'Qutb Minar', 'New Delhi', 'Inde',  17);
Insert into Etapes values('C0076', 1, 'Senso-ji', 'Tokyo', 'Japon',  4);
Insert into Etapes values('C0076', 2, 'Tokyo Skytree', 'Tokyo', 'Japon',  4);
Insert into Etapes values('C0076', 3, 'Big Ben', 'Londres', 'Angleterre',  4);
Insert into Etapes values('C0076', 4, 'British Museum', 'Londres', 'Angleterre',  13);
Insert into Etapes values('C0077', 1, 'Senso-ji', 'Tokyo', 'Japon',  4);
Insert into Etapes values('C0077', 2, 'Tokyo Skytree', 'Tokyo', 'Japon',  4);
Insert into Etapes values('C0077', 3, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  4);
Insert into Etapes values('C0077', 4, 'Corcovado', 'Rio de Janeiro', 'Bresil',  15);
Insert into Etapes values('C0078', 1, 'Senso-ji', 'Tokyo', 'Japon',  6);
Insert into Etapes values('C0078', 2, 'Tokyo Skytree', 'Tokyo', 'Japon',  6);
Insert into Etapes values('C0078', 3, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  6);
Insert into Etapes values('C0078', 4, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  18);
Insert into Etapes values('C0079', 1, 'Senso-ji', 'Tokyo', 'Japon',  7);
Insert into Etapes values('C0079', 2, 'Tokyo Skytree', 'Tokyo', 'Japon',  7);
Insert into Etapes values('C0079', 3, 'Central Park', 'New York', 'Etats-Unis',  7);
Insert into Etapes values('C0079', 4, 'Statue de la Liberte', 'New York', 'Etats-Unis',  23);
Insert into Etapes values('C0080', 1, 'Senso-ji', 'Tokyo', 'Japon',  5);
Insert into Etapes values('C0080', 2, 'Tokyo Skytree', 'Tokyo', 'Japon',  5);
Insert into Etapes values('C0080', 3, 'Musee de la Kasbah', 'Tanger', 'Maroc',  5);
Insert into Etapes values('C0080', 4, 'Grottes Hercule', 'Tanger', 'Maroc',  17);
Insert into Etapes values('C0081', 1, 'Senso-ji', 'Tokyo', 'Japon',  2);
Insert into Etapes values('C0081', 2, 'Tokyo Skytree', 'Tokyo', 'Japon',  2);
Insert into Etapes values('C0081', 3, 'Parc du Retiro', 'Madrid', 'Espagne',  2);
Insert into Etapes values('C0081', 4, 'Puerta del Sol', 'Madrid', 'Espagne',  6);
Insert into Etapes values('C0082', 1, 'Parc du Retiro', 'Madrid', 'Espagne',  6);
Insert into Etapes values('C0082', 2, 'Puerta del Sol', 'Madrid', 'Espagne',  6);
Insert into Etapes values('C0082', 3, 'Tour Eiffel', 'Paris', 'France',  6);
Insert into Etapes values('C0082', 4, 'Champs-elysees', 'Paris', 'France',  20);
Insert into Etapes values('C0083', 1, 'Parc du Retiro', 'Madrid', 'Espagne',  3);
Insert into Etapes values('C0083', 2, 'Puerta del Sol', 'Madrid', 'Espagne',  3);
Insert into Etapes values('C0083', 3, 'Kremlin de Moscou', 'Moscou', 'Russie',  3);
Insert into Etapes values('C0083', 4, 'Parc Gorki', 'Moscou', 'Russie',  10);
Insert into Etapes values('C0084', 1, 'Parc du Retiro', 'Madrid', 'Espagne',  5);
Insert into Etapes values('C0084', 2, 'Puerta del Sol', 'Madrid', 'Espagne',  5);
Insert into Etapes values('C0084', 3, 'Fort Rouge', 'New Delhi', 'Inde',  5);
Insert into Etapes values('C0084', 4, 'Qutb Minar', 'New Delhi', 'Inde',  16);
Insert into Etapes values('C0085', 1, 'Parc du Retiro', 'Madrid', 'Espagne',  5);
Insert into Etapes values('C0085', 2, 'Puerta del Sol', 'Madrid', 'Espagne',  5);
Insert into Etapes values('C0085', 3, 'Big Ben', 'Londres', 'Angleterre',  5);
Insert into Etapes values('C0085', 4, 'British Museum', 'Londres', 'Angleterre',  18);
Insert into Etapes values('C0086', 1, 'Parc du Retiro', 'Madrid', 'Espagne',  3);
Insert into Etapes values('C0086', 2, 'Puerta del Sol', 'Madrid', 'Espagne',  3);
Insert into Etapes values('C0086', 3, 'Christ Redempteur', 'Rio de Janeiro', 'Bresil',  3);
Insert into Etapes values('C0086', 4, 'Corcovado', 'Rio de Janeiro', 'Bresil',  10);
Insert into Etapes values('C0087', 1, 'Parc du Retiro', 'Madrid', 'Espagne',  2);
Insert into Etapes values('C0087', 2, 'Puerta del Sol', 'Madrid', 'Espagne',  2);
Insert into Etapes values('C0087', 3, 'Rijkmuseum Amsterdam', 'Amsterdam', 'Pays-Bas',  2);
Insert into Etapes values('C0087', 4, 'Heineken Experience', 'Amsterdam', 'Pays-Bas',  8);
Insert into Etapes values('C0088', 1, 'Parc du Retiro', 'Madrid', 'Espagne',  3);
Insert into Etapes values('C0088', 2, 'Puerta del Sol', 'Madrid', 'Espagne',  3);
Insert into Etapes values('C0088', 3, 'Central Park', 'New York', 'Etats-Unis',  3);
Insert into Etapes values('C0088', 4, 'Statue de la Liberte', 'New York', 'Etats-Unis',  11);
Insert into Etapes values('C0089', 1, 'Parc du Retiro', 'Madrid', 'Espagne',  2);
Insert into Etapes values('C0089', 2, 'Puerta del Sol', 'Madrid', 'Espagne',  2);
Insert into Etapes values('C0089', 3, 'Musee de la Kasbah', 'Tanger', 'Maroc',  2);
Insert into Etapes values('C0089', 4, 'Grottes Hercule', 'Tanger', 'Maroc',  8);
Insert into Etapes values('C0090', 1, 'Parc du Retiro', 'Madrid', 'Espagne',  6);
Insert into Etapes values('C0090', 2, 'Puerta del Sol', 'Madrid', 'Espagne',  6);
Insert into Etapes values('C0090', 3, 'Senso-ji', 'Tokyo', 'Japon',  6);
Insert into Etapes values('C0090', 4, 'Tokyo Skytree', 'Tokyo', 'Japon',  18);
